project:
  type: book
  output-dir: docs

book:
  title: "R Practicals for NST Part III Systems Biology"
  author: "Alexia Cardona"
  
  chapters:
    - index.qmd
    - practical1.qmd
    
    - part: "Practical 1 Notes"
      chapters: 
        - getting-started.qmd
        - intro-r-programming.qmd
        - starting-with-data.qmd

    - references.qmd

bibliography: references.bib
csl: nature.csl

format:
  html:
    theme: cosmo
    code-overflow: wrap
    
editor: visual

